
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jun 28 22:14:45 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 12;
  public static final int CHAR = 42;
  public static final int CONST = 7;
  public static final int EQUALS = 19;
  public static final int LOWER = 23;
  public static final int HASH = 36;
  public static final int LPAREN = 10;
  public static final int GREATER = 21;
  public static final int SEMI = 5;
  public static final int LOWEREQUAL = 24;
  public static final int MINUS = 15;
  public static final int RPAREN = 11;
  public static final int AND = 30;
  public static final int OR = 31;
  public static final int COMMA = 6;
  public static final int INC = 28;
  public static final int DIV = 17;
  public static final int PLUS = 14;
  public static final int MAIN = 35;
  public static final int IF = 33;
  public static final int BOOLEAN = 41;
  public static final int EOF = 0;
  public static final int RETURN = 25;
  public static final int RBRACKET = 13;
  public static final int EQUAL = 8;
  public static final int NEW = 32;
  public static final int error = 1;
  public static final int DISTINCT = 20;
  public static final int MUL = 16;
  public static final int NUMBER = 39;
  public static final int MOD = 18;
  public static final int IDENT = 40;
  public static final int VOID = 9;
  public static final int GREATEREQUAL = 22;
  public static final int COLON = 38;
  public static final int LBRACE = 3;
  public static final int ELSE = 34;
  public static final int READ = 27;
  public static final int GOTO = 37;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int DEC = 29;
  public static final int PRINT = 26;
}

